#pragma once

#ifndef F_CPU
#define F_CPU 16000000UL
#endif

#define SYSTEM_TICK_MS 1UL
#define TIMER_MAX_COUNT 3

#define UART_BAUD_RATE 38400
#define UART_RX_BUFFER_SIZE 128
#define UART_TX_BUFFER_SIZE 128
#define UART_SAFETY_LOOP_LIMIT 256

#define HTTP_REQUEST_BUFFER_SIZE 128
#define HTTP_RESPONSE_BUFFER_SIZE 128
#define HTTP_MAX_HOST_LEN 64
#define HTTP_HEADER_END_LEN 4

#define MAX_HANDLERS 5
#define ALLOWED_HOST "Admin"

#define ADC_CHANNEL_MASK 0x07
#define ADC_MUX_MASK 0xF0
#define ADC_PRESCALER_128 0x07
#define ADC_TIMEOUT_CYCLES 1000

#define STR_LEN_ADC_PATH 10
#define STR_LEN_GPIO_TOGGLE 13
#define STR_LEN_GPIO_SET 10
#define STR_LEN_GPIO_GET 10
#define STR_LEN_PWM_SET 9